databases:
  - name: qr
    databaseName: qr
    user: qr

services:
  - type: web
    name: qr
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qr
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false